listening-port=3478

realm=darkchat.fr

fingerprint

use-auth-secret
static-auth-secret=TA_CLE_SECRETE

min-port=50101
max-port=50201

no-multicast-peers
no-cli

verbose
simple-log
log-file=stdout

external-ip=82.26.80.184
